import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import checkFile from "eslint-plugin-check-file";
import jsdoc from "eslint-plugin-jsdoc";
import prettierConfig from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettierConfig,
  {
    plugins: {
      "check-file": checkFile,
      jsdoc: jsdoc,
    },
    settings: {
      jsdoc: {
        mode: "typescript",
      },
    },
    rules: {
      // 1. Absolute Imports (@/)
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["./../*", "../../*"],
              message: "Please use absolute imports (e.g. @/...) instead of relative parent imports.",
            },
          ],
        },
      ],

      // 2. Naming Conventions (Files)
      "check-file/filename-naming-convention": [
        "error",
        {
          "**/utils/**/*.{ts,tsx}": "KEBAB_CASE",
          "**/lib/**/*.{ts,tsx}": "KEBAB_CASE",
          "**/hooks/**/*.{ts,tsx}": "KEBAB_CASE",
          "**/components/**/*.{tsx}": "PASCAL_CASE",
        },
        {
          ignoreMiddleExtensions: true,
        },
      ],
      "check-file/folder-naming-convention": [
        "error",
        {
          "src/**/!(__tests__)": "KEBAB_CASE",
        },
      ],

      // 3. JSDoc Requirements
      "jsdoc/require-jsdoc": "off",
      "jsdoc/require-description": "off",
      "jsdoc/require-param": "off",
      "jsdoc/require-returns": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-empty-object-type": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "no-unused-vars": "off",
    },
  },
  // 4. Global Ignores (Autogenerated files)
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "src/generated/**",
    "prisma/seed.ts",
    "playwright-report/**",
    "test-results/**",
    "coverage/**",
    "scripts/**",
  ]),
]);

export default eslintConfig;
