"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  BarChart3,
  TrendingUp,
  AlertTriangle,
  Lightbulb,
  Loader2,
  X,
  Sparkles,
} from "lucide-react";
import { Button } from "@/components/ui/button";

interface WeeklyReport {
  summary: string;
  highlights: string[];
  concerns: string[];
  recommendations: string[];
  performanceScore: number;
}

interface ReportData {
  businessName: string;
  periodStart: string;
  periodEnd: string;
  bookingsTotal: number;
  bookingsCompleted: number;
  bookingsCancelled: number;
  newContacts: number;
  messagesReceived: number;
  staffCount: number;
}

/**
 * Component to display a weekly business report generated by AI.
 */
export function WeeklyReportCard() {
  const [isOpen, setIsOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState<WeeklyReport | null>(null);
  const [data, setData] = useState<ReportData | null>(null);
  const [error, setError] = useState<string | null>(null);

  const fetchReport = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/ai/weekly-report");
      if (!res.ok) throw new Error("Failed to generate report");
      const json = await res.json();
      setReport(json.report);
      setData(json.data);
      setIsOpen(true);
    } catch {
      setError("Could not generate report. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <Button
        variant="outline"
        size="sm"
        onClick={fetchReport}
        disabled={loading}
        className="gap-2"
      >
        {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <BarChart3 className="h-4 w-4" />}
        Weekly Report
      </Button>

      {error && <p className="text-destructive mt-1 text-xs">{error}</p>}

      <AnimatePresence>
        {isOpen && report && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
            onClick={() => setIsOpen(false)}
          >
            <motion.div
              initial={{ scale: 0.9, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.9, y: 20 }}
              onClick={(e) => e.stopPropagation()}
              className="bg-card max-h-[85vh] w-full max-w-lg overflow-y-auto rounded-2xl border p-6 shadow-2xl"
            >
              {/* Header */}
              <div className="mb-4 flex items-start justify-between">
                <div>
                  <h2 className="flex items-center gap-2 text-lg font-bold">
                    <Sparkles className="text-primary h-5 w-5" />
                    Weekly Report
                  </h2>
                  {data && (
                    <p className="text-muted-foreground text-xs">
                      {data.periodStart} → {data.periodEnd}
                    </p>
                  )}
                </div>
                <button onClick={() => setIsOpen(false)} className="hover:bg-muted rounded-lg p-1">
                  <X className="h-5 w-5" />
                </button>
              </div>

              {/* Performance Score */}
              <div className="from-primary/10 to-primary/5 mb-4 flex items-center gap-3 rounded-xl bg-gradient-to-r p-4">
                <div className="relative h-14 w-14">
                  <svg className="h-14 w-14 -rotate-90" viewBox="0 0 36 36">
                    <path
                      d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="3"
                      className="text-muted/20"
                    />
                    <path
                      d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="3"
                      strokeDasharray={`${report.performanceScore}, 100`}
                      className="text-primary"
                    />
                  </svg>
                  <span className="absolute inset-0 flex items-center justify-center text-sm font-bold">
                    {report.performanceScore}
                  </span>
                </div>
                <div className="flex-1">
                  <p className="text-sm font-medium">Performance Score</p>
                  <p className="text-muted-foreground text-xs">
                    {report.performanceScore >= 80
                      ? "Excellent week!"
                      : report.performanceScore >= 60
                        ? "Good week with room to improve"
                        : "Some areas need attention"}
                  </p>
                </div>
              </div>

              {/* Summary */}
              <p className="text-foreground/90 mb-4 text-sm leading-relaxed">{report.summary}</p>

              {/* Highlights */}
              {report.highlights.length > 0 && (
                <div className="mb-4">
                  <h3 className="mb-2 flex items-center gap-1.5 text-sm font-semibold text-green-600 dark:text-green-400">
                    <TrendingUp className="h-4 w-4" />
                    Highlights
                  </h3>
                  <ul className="space-y-1">
                    {report.highlights.map((h, i) => (
                      <li key={i} className="text-muted-foreground flex items-start gap-2 text-sm">
                        <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-green-500" />
                        {h}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Concerns */}
              {report.concerns.length > 0 && (
                <div className="mb-4">
                  <h3 className="mb-2 flex items-center gap-1.5 text-sm font-semibold text-amber-600 dark:text-amber-400">
                    <AlertTriangle className="h-4 w-4" />
                    Concerns
                  </h3>
                  <ul className="space-y-1">
                    {report.concerns.map((c, i) => (
                      <li key={i} className="text-muted-foreground flex items-start gap-2 text-sm">
                        <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-amber-500" />
                        {c}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Recommendations */}
              {report.recommendations.length > 0 && (
                <div>
                  <h3 className="mb-2 flex items-center gap-1.5 text-sm font-semibold text-blue-600 dark:text-blue-400">
                    <Lightbulb className="h-4 w-4" />
                    Recommendations
                  </h3>
                  <ul className="space-y-1">
                    {report.recommendations.map((r, i) => (
                      <li key={i} className="text-muted-foreground flex items-start gap-2 text-sm">
                        <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-blue-500" />
                        {r}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Quick Stats */}
              {data && (
                <div className="mt-4 grid grid-cols-3 gap-2 border-t pt-4">
                  <div className="bg-muted/50 rounded-lg p-2 text-center">
                    <p className="text-lg font-bold">{data.bookingsTotal}</p>
                    <p className="text-muted-foreground text-[10px]">Bookings</p>
                  </div>
                  <div className="bg-muted/50 rounded-lg p-2 text-center">
                    <p className="text-lg font-bold">{data.newContacts}</p>
                    <p className="text-muted-foreground text-[10px]">New Contacts</p>
                  </div>
                  <div className="bg-muted/50 rounded-lg p-2 text-center">
                    <p className="text-lg font-bold">{data.messagesReceived}</p>
                    <p className="text-muted-foreground text-[10px]">Messages</p>
                  </div>
                </div>
              )}
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
